### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by mcxiaochenn** [LittleSkinChina/premium-verification#1]
详细信息：cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://login.microsoftonline.com/consumers/oauth2/v2.0/token

.env
MICROSOFT_CLIENT_ID=id
MICROSOFT_CLIENT_SECRET=id@passwd
MICROSOFT_LOGIN_REDIRECT_URI=https://url/microsoftoidc/callback
MICROSOFT_PREMIUM_REDIRECT_URI=https://url/user/premium/callback

**Comment by tnqzh123** [comment]
要么是你的服务器的环境有问题，要么是你的服务器的网络有问题。

请自行 STFW。
